/**
 * Tareas para estimar en Scope it. Se plantean como si fueran para una jam de 48 horas, con un
 * equipo pequeño y arte provisional, y hay que decir cuántas horas de trabajo llevan.
 *
 * Cada entrada:
 *   key   - identificador estable (se usa para no repetir casos recientes)
 *   title - etiqueta corta para títulos y glosario
 *   text  - descripción de la tarea
 */
module.exports = [
  // ---- Sistemas y programación ----
  { key: 'guardado-ranuras', title: 'Guardado con tres ranuras', text: 'Un sistema de guardado con tres ranuras en un juego 2D, incluido el menú para elegir ranura y borrarla.' },
  { key: 'menu-pausa', title: 'Menú de pausa', text: 'Un menú de pausa con continuar, control de volumen de música y efectos, y salir al menú principal.' },
  { key: 'jefe-tres-fases', title: 'Jefe con tres fases', text: 'Un jefe final con tres fases y un ataque distinto en cada una, con arte provisional.' },
  { key: 'sistema-dialogos', title: 'Sistema de diálogos', text: 'Un sistema de diálogos con caja de texto, retrato del personaje, texto que aparece letra a letra y elección entre dos respuestas.' },
  { key: 'inventario-basico', title: 'Inventario de 12 huecos', text: 'Un inventario de 12 huecos con arrastrar y soltar y apilado de objetos iguales.' },
  { key: 'tienda-mejoras', title: 'Tienda de mejoras', text: 'Una tienda donde comprar tres mejoras permanentes con las monedas recogidas en los niveles.' },
  { key: 'segundo-idioma', title: 'Segundo idioma', text: 'Traducir toda la interfaz del juego a un segundo idioma, unas 80 cadenas de texto, con selector en opciones.' },
  { key: 'soporte-mando', title: 'Soporte de mando', text: 'Que el juego se pueda jugar con mando además de teclado, incluida la navegación por los menús.' },
  { key: 'tutorial-integrado', title: 'Tutorial integrado', text: 'Un tutorial dentro del primer nivel que enseña a saltar, atacar y esquivar sin pantallas de texto.' },
  { key: 'minimapa', title: 'Minimapa', text: 'Un minimapa en una esquina que muestra la sala actual, las salas visitadas y la posición del jugador.' },
  { key: 'mazmorras-procedurales', title: 'Mazmorras procedurales', text: 'Generación procedural de mazmorras con cinco tipos de sala conectadas y una sala de jefe al final.' },
  { key: 'combos', title: 'Combos de tres golpes', text: 'Un sistema de combos de tres golpes encadenados, con las animaciones ya hechas.' },
  { key: 'lluvia', title: 'Lluvia', text: 'Lluvia con partículas y sonido que empieza y termina de forma aleatoria durante el nivel.' },
  { key: 'ciclo-dia-noche', title: 'Ciclo de día y noche', text: 'Un ciclo de día y noche de cinco minutos que cambia la iluminación y hace aparecer enemigos distintos.' },
  { key: 'records-local', title: 'Tabla de récords local', text: 'Una tabla de récords guardada en el ordenador, con nombre de tres letras al estilo arcade.' },
  { key: 'records-online', title: 'Tabla de récords online', text: 'Una tabla de récords online compartida entre todos los jugadores.' },
  { key: 'dos-jugadores-local', title: 'Dos jugadores en local', text: 'Modo de dos jugadores en la misma pantalla, cada uno con su mando.' },
  { key: 'dos-jugadores-online', title: 'Dos jugadores online', text: 'Modo de dos jugadores por internet.' },
  { key: 'logros', title: 'Diez logros', text: 'Diez logros con una notificación en pantalla al conseguirlos y una pantalla donde verlos.' },
  { key: 'pantalla-titulo', title: 'Pantalla de título', text: 'Una pantalla de título con logo animado, música y botones de jugar, opciones y salir.' },
  { key: 'creditos', title: 'Créditos', text: 'Una pantalla de créditos con desplazamiento automático y botón para saltarla.' },
  { key: 'opciones-graficas', title: 'Opciones gráficas', text: 'Un menú de opciones con resolución, pantalla completa y calidad gráfica, que se guarde entre sesiones.' },
  { key: 'crafteo', title: 'Crafteo con diez recetas', text: 'Un sistema de crafteo con diez recetas y una mesa de trabajo donde combinarlas.' },
  { key: 'mapa-del-mundo', title: 'Mapa del mundo', text: 'Un mapa del mundo con seis niveles seleccionables que se desbloquean en orden y guardan el progreso.' },
  { key: 'accesibilidad-basica', title: 'Accesibilidad básica', text: 'Remapeo de teclas y un modo para daltonismo que cambie los colores clave del juego.' },
  { key: 'zonas-de-agua', title: 'Zonas de agua', text: 'Zonas de agua donde el jugador nada más lento, flota y tiene una animación distinta.' },
  { key: 'sistema-de-danio', title: 'Sistema de daño', text: 'Un sistema de daño con números flotantes, parpadeo del personaje golpeado y sonido de golpe.' },
  { key: 'enemigo-volador', title: 'Enemigo volador', text: 'Un enemigo volador que sigue al jugador y esquiva los obstáculos sencillos del nivel.' },
  { key: 'coleccionables', title: 'Veinte coleccionables', text: 'Veinte coleccionables repartidos por los niveles, con contador en la interfaz y guardado de cuáles tienes.' },
  { key: 'vidas-y-game-over', title: 'Vidas y game over', text: 'Un sistema de vidas con reaparición en el último punto de control y pantalla de game over.' },
  { key: 'sistema-particulas', title: 'Partículas del juego', text: 'Efectos de partículas para el salto, el golpe, la muerte y recoger monedas.' },
  { key: 'pantalla-carga', title: 'Pantalla de carga', text: 'Una pantalla de carga entre niveles con barra de progreso y un consejo aleatorio.' },
  { key: 'doble-salto', title: 'Doble salto', text: 'Añadir un doble salto con su animación y sonido a un plataformas que ya tiene salto.' },
  { key: 'dash', title: 'Dash', text: 'Un dash con invulnerabilidad breve, partículas y tiempo de recarga.' },
  { key: 'escalar-paredes', title: 'Salto de pared', text: 'Que el personaje pueda agarrarse a las paredes y saltar desde ellas.' },
  { key: 'sistema-oleadas', title: 'Oleadas de enemigos', text: 'Un sistema de oleadas de enemigos con cuenta atrás entre oleadas y dificultad creciente.' },
  { key: 'ia-patrulla-persigue', title: 'Enemigos que patrullan y persiguen', text: 'Enemigos que patrullan y persiguen al jugador al verlo, y vuelven a la patrulla si lo pierden.' },
  { key: 'jefe-simple', title: 'Jefe sencillo', text: 'Un jefe con dos ataques alternos y una barra de vida propia.' },
  { key: 'arma-secundaria', title: 'Arma secundaria', text: 'Un arma secundaria con munición limitada y recogida de munición por el nivel.' },
  { key: 'cajas-empujables', title: 'Cajas empujables', text: 'Cajas que se empujan y sirven para llegar a sitios altos.' },
  { key: 'interruptores-puertas', title: 'Interruptores y puertas', text: 'Interruptores que abren puertas, con respuesta visual y sonora.' },
  { key: 'checkpoints', title: 'Puntos de control', text: 'Puntos de control con reaparición y animación de activación.' },
  { key: 'vida-corazones', title: 'Vida por corazones', text: 'Vida por corazones, con corazones que se recogen y máximo ampliable.' },
  { key: 'camara-limites', title: 'Cámara con límites', text: 'Una cámara que sigue al jugador con suavizado y no sale de los límites del nivel.' },
  { key: 'menu-principal-completo', title: 'Menú principal completo', text: 'Menú principal con jugar, continuar, opciones y salir, navegable con teclado y mando.' },
  { key: 'guardado-automatico', title: 'Guardado automático', text: 'Guardado automático al pasar cada nivel y carga al iniciar.' },
  { key: 'remapeo-controles', title: 'Remapeo de controles', text: 'Un menú para cambiar las teclas de cada acción y guardarlo.' },
  { key: 'daltonismo', title: 'Modo daltonismo', text: 'Un modo para daltonismo que cambia los colores clave del juego.' },
  { key: 'subtitulos', title: 'Subtítulos', text: 'Subtítulos para las voces con opción de activarlos.' },
  { key: 'pantalla-resultados', title: 'Pantalla de resultados', text: 'Pantalla de resultados al final del nivel con tiempo, muertes y estrellas.' },
  { key: 'mejoras-permanentes', title: 'Árbol de mejoras', text: 'Un árbol de tres mejoras permanentes que se compran entre partidas.' },
  { key: 'barra-rapida', title: 'Barra rápida', text: 'Una barra rápida de cuatro huecos para cambiar de objeto con la rueda del ratón.' },
  { key: 'minijuego-cerraduras', title: 'Minijuego de cerraduras', text: 'Un minijuego de forzar cerraduras con un temporizador.' },
  { key: 'generador-nombres', title: 'Generador de nombres', text: 'Un generador de nombres aleatorios para los personajes.' },
  { key: 'cinematica-final', title: 'Cinemática final', text: 'Una cinemática final de 20 segundos con texto y música.' },
  { key: 'modo-foto', title: 'Modo foto', text: 'Un modo foto que oculta la interfaz y permite mover la cámara.' },
  { key: 'estadisticas', title: 'Pantalla de estadísticas', text: 'Una pantalla de estadísticas: enemigos derrotados, tiempo jugado, muertes.' },

  // ---- Arte ----
  { key: 'animaciones-protagonista', title: 'Animaciones del protagonista', text: 'Animaciones de quieto, andar, saltar, atacar y morir para el protagonista, en pixel art de 32 píxeles.' },
  { key: 'arte-nivel-completo', title: 'Arte de un nivel', text: 'El arte de un nivel completo: un conjunto de 30 tiles y tres capas de fondo con parallax.' },
  { key: 'enemigo-que-dispara', title: 'Enemigo que dispara', text: 'Un enemigo nuevo que patrulla y dispara al ver al jugador, con su arte y su sonido.' },
  { key: 'modelo-protagonista-3d', title: 'Protagonista en 3D', text: 'Un modelo 3D low poly del protagonista con texturas y un rig básico para animarlo.' },
  { key: 'cinematica-intro', title: 'Cinemática de introducción', text: 'Una cinemática de introducción de 30 segundos hecha dentro del propio motor, con texto y música.' },
  { key: 'personaje-secundario', title: 'Personaje secundario', text: 'Un personaje secundario en pixel art con animaciones de quieto y hablar.' },
  { key: 'tres-enemigos-arte', title: 'Tres enemigos pequeños', text: 'El arte y animaciones de tres enemigos pequeños en pixel art.' },
  { key: 'jefe-arte', title: 'Arte de un jefe', text: 'El arte y animaciones de un jefe grande, con dos ataques y muerte.' },
  { key: 'tileset-nieve', title: 'Tiles de nieve', text: 'Un segundo conjunto de tiles para un bioma de nieve, con sus decoraciones.' },
  { key: 'fondos-parallax', title: 'Fondos con parallax', text: 'Tres capas de fondo con parallax para un nivel.' },
  { key: 'iconos-interfaz', title: 'Veinte iconos', text: 'Veinte iconos de interfaz coherentes entre sí.' },
  { key: 'logo-juego', title: 'Logo del juego', text: 'El logo del juego para el menú y la página de itch.io.' },
  { key: 'portada-itch', title: 'Portada y banner', text: 'La imagen de portada y el banner para itch.io.' },
  { key: 'retratos-dialogo', title: 'Retratos de diálogo', text: 'Retratos de cuatro personajes con tres expresiones cada uno.' },
  { key: 'animacion-ataque', title: 'Animación de ataque', text: 'Una animación de ataque con tres golpes encadenados en pixel art.' },
  { key: 'efectos-golpe', title: 'Efectos de golpe', text: 'Efectos visuales de golpe, chispas y polvo al aterrizar.' },
  { key: 'modelo-arma-3d', title: 'Arma en 3D', text: 'Un modelo 3D de un arma con texturas listo para el motor.' },
  { key: 'escenario-3d-modular', title: 'Kit modular 3D', text: 'Un conjunto modular 3D de paredes, suelos y puertas para montar niveles.' },
  { key: 'iluminacion-nivel', title: 'Iluminación de un nivel', text: 'La iluminación de un nivel 3D con luces horneadas.' },
  { key: 'shader-agua-3d', title: 'Shader de agua', text: 'Un shader de agua con ondas y reflejos sencillos.' },
  { key: 'cursor-personalizado', title: 'Cursor personalizado', text: 'Un cursor personalizado con estados normal, sobre botón y pulsado.' },
  { key: 'fuente-pixel', title: 'Fuente pixel art', text: 'Una fuente de pixel art propia con números y acentos.' },
  { key: 'pantalla-titulo-arte', title: 'Ilustración de título', text: 'La ilustración de la pantalla de título.' },

  // ---- Audio ----
  { key: 'pasos-por-suelo', title: 'Pasos según el suelo', text: 'Sonido de pasos que cambia según el suelo que se pisa: hierba, piedra y madera.' },
  { key: 'musica-por-capas', title: 'Música por capas', text: 'Música que añade una capa de percusión cuando hay enemigos cerca y la quita cuando se alejan.' },
  { key: 'tema-principal', title: 'Tema principal', text: 'Un tema musical principal de dos minutos en loop.' },
  { key: 'tema-jefe', title: 'Tema del jefe', text: 'Un tema musical para el jefe, más intenso, en loop.' },
  { key: 'tema-menu', title: 'Tema del menú', text: 'Un tema tranquilo para el menú.' },
  { key: 'sfx-basicos', title: 'Veinte efectos básicos', text: 'Veinte efectos de sonido básicos: salto, golpe, moneda, puerta, botones.' },
  { key: 'sfx-enemigos', title: 'Sonidos de enemigos', text: 'Los sonidos de tres enemigos: aparecer, atacar y morir.' },
  { key: 'voces-personaje', title: 'Voces del protagonista', text: 'Grabar y editar diez frases cortas del protagonista.' },
  { key: 'mezcla-final', title: 'Mezcla final', text: 'La mezcla final de todo el audio con volúmenes equilibrados y grupos.' },
  { key: 'audio-espacial-setup', title: 'Audio espacial', text: 'Configurar audio espacial para enemigos y objetos en un nivel 3D.' },
  { key: 'stingers', title: 'Cuatro stingers', text: 'Cuatro stingers: victoria, derrota, logro y descubrimiento.' },
  { key: 'ambientes', title: 'Tres ambientes', text: 'Tres sonidos de ambiente en loop: bosque, cueva y ciudad.' },
  { key: 'sonidos-interfaz', title: 'Sonidos de interfaz', text: 'Sonidos para toda la interfaz: navegar, aceptar, cancelar, error.' },
  { key: 'menu-volumen', title: 'Menú de volumen', text: 'Un menú de volumen con música, efectos y voces por separado conectado al mezclador.' },

  // ---- Diseño, narrativa y producción ----
  { key: 'build-web', title: 'Build para web', text: 'Exportar el juego a web, probarlo en dos navegadores distintos y subirlo a itch.io.' },
  { key: 'trailer', title: 'Tráiler', text: 'Un tráiler de 40 segundos grabado con OBS y montado con música.' },
  { key: 'pagina-itch', title: 'Página de itch.io', text: 'La página de itch.io con capturas, descripción, controles y una imagen de portada.' },
  { key: 'gdd-una-pagina', title: 'Diseño en una página', text: 'Un documento de diseño de una página con la idea, el bucle y el alcance.' },
  { key: 'diseno-cinco-niveles', title: 'Cinco niveles en papel', text: 'Diseñar sobre papel cinco niveles con progresión de dificultad.' },
  { key: 'montar-nivel', title: 'Montar un nivel', text: 'Montar un nivel en el motor a partir de un diseño en papel, con tiles y enemigos.' },
  { key: 'balancear-armas', title: 'Balancear tres armas', text: 'Balancear tres armas probándolas y ajustando números.' },
  { key: 'playtest-sesion', title: 'Sesión de pruebas', text: 'Organizar una sesión de prueba con cinco personas y apuntar los problemas.' },
  { key: 'guion-historia', title: 'Historia y tres escenas', text: 'Escribir la historia completa en una página y los diálogos de tres escenas.' },
  { key: 'dialogos-npc', title: 'Diálogos de diez personajes', text: 'Escribir los diálogos de diez personajes secundarios con tres frases cada uno.' },
  { key: 'nombres-lugares', title: 'Veinte lugares', text: 'Inventar los nombres y una línea de descripción para veinte lugares del mapa.' },
  { key: 'textos-interfaz', title: 'Textos de interfaz', text: 'Escribir todos los textos de la interfaz y los mensajes de error.' },
  { key: 'descripciones-objetos', title: 'Treinta descripciones', text: 'Escribir las descripciones de treinta objetos del inventario.' },
  { key: 'tutorial-textos', title: 'Carteles del tutorial', text: 'Escribir y colocar los carteles del tutorial.' },
  { key: 'logros-diseno', title: 'Diseñar diez logros', text: 'Diseñar diez logros y sus condiciones.' },
  { key: 'plan-jam', title: 'Plan de la jam', text: 'Planificar las 48 horas de la jam por bloques y repartir tareas.' },
  { key: 'repo-setup', title: 'Preparar el repositorio', text: 'Preparar el repositorio con gitignore, ramas y LFS para el equipo.' },
  { key: 'build-tres-plataformas', title: 'Tres plataformas', text: 'Exportar y probar en Windows, Mac y web.' },
  { key: 'video-gameplay', title: 'Un minuto de gameplay', text: 'Grabar un minuto de gameplay limpio para la página.' },
  { key: 'devlog-post', title: 'Un devlog', text: 'Escribir un devlog con capturas y lo aprendido.' },
  { key: 'postmortem-doc', title: 'Postmortem', text: 'Hacer un postmortem con el equipo y escribirlo.' },
  { key: 'creditos-licencias', title: 'Créditos y licencias', text: 'Recopilar créditos y licencias de todos los assets usados.' },
  { key: 'pruebas-mando', title: 'Pruebas con mando', text: 'Probar todo el juego con mando y arreglar lo que no funcione.' },
  { key: 'arreglar-diez-bugs', title: 'Diez bugs pequeños', text: 'Arreglar una lista de diez bugs pequeños encontrados en pruebas.' },
  { key: 'optimizar-web', title: 'Build web ligera', text: 'Optimizar la build web para que pese menos de 50 MB y cargue rápido.' },
  { key: 'texto-grande', title: 'Texto grande', text: 'Opción de tamaño de texto grande en toda la interfaz.' },
];
