/**
 * Casos de Triaje: mensajes de gente atascada, escritos como llegan de verdad al canal de
 * ayuda, vagos y sin detalles. La gracia es preguntar bien antes de responder.
 *
 * Cada entrada:
 *   key        - identificador estable (se usa para no repetir casos recientes)
 *   discipline - disciplina a la que apunta el caso
 *   title      - etiqueta corta para títulos y glosario
 *   text       - el mensaje tal cual lo escribiría la persona atascada
 */
const P = 'Programación';
const A = 'Arte';
const S = 'Audio';
const D = 'Diseño';
const N = 'Narrativa';
const R = 'Producción';

module.exports = [
  // ---- Programación ----
  { key: 'atraviesa-suelo', discipline: P, title: 'Atraviesa el suelo', text: 'Mi personaje atraviesa el suelo a veces, sobre todo cuando cae rápido. ¿Qué hago?' },
  { key: 'salto-fallo', discipline: P, title: 'El salto falla', text: 'El salto no funciona bien, a veces salta y a veces no. Ya lo he mirado mil veces.' },
  { key: 'tirones-movil', discipline: P, title: 'Tirones en móvil', text: 'En mi PC va perfecto pero en el móvil de mi compañero va a tirones.' },
  { key: 'null-reference', discipline: P, title: 'NullReferenceException', text: 'Me sale NullReferenceException y no entiendo por qué, ayer funcionaba.' },
  { key: 'build-se-cierra', discipline: P, title: 'La build se cierra', text: 'Exporté el juego y al abrirlo se cierra al instante. En el editor va bien.' },
  { key: 'webgl-negro', discipline: P, title: 'WebGL en negro', text: 'Subí la build de WebGL a itch.io y se queda en pantalla negra.' },
  { key: 'guardado-build', discipline: P, title: 'No guarda en la build', text: 'El guardado funciona en el editor pero en la build no guarda nada.' },
  { key: 'enemigos-paredes', discipline: P, title: 'Enemigos por las paredes', text: 'Los enemigos atraviesan las paredes cuando persiguen al jugador.' },
  { key: 'disparo-doble', discipline: P, title: 'Dispara dos veces', text: 'Al pulsar el botón de disparo a veces dispara dos veces seguidas.' },
  { key: 'merge-escena', discipline: P, title: 'Escena vacía tras merge', text: 'Hicimos merge en git y ahora la escena principal está vacía. Socorro.' },
  { key: 'fps-enemigos', discipline: P, title: 'FPS por los suelos', text: 'Cada vez que aparecen muchos enemigos los FPS se van al suelo.' },
  { key: 'camara-tiembla', discipline: P, title: 'Cámara que tiembla', text: 'La cámara tiembla cuando sigue al personaje y marea un montón.' },
  { key: 'animacion-atascada', discipline: P, title: 'Atascado en la animación', text: 'El personaje se queda atascado en la animación de ataque y ya no se mueve.' },
  { key: 'duplicados', discipline: P, title: 'Objetos que se duplican', text: 'Los objetos se duplican solos hasta que el juego se congela.' },
  { key: 'timer-rapido', discipline: P, title: 'Temporizador acelerado', text: 'El temporizador del juego corre más rápido en los ordenadores potentes.' },
  { key: 'fisica-explota', discipline: P, title: 'Física que explota', text: 'Al chocar dos cajas salen disparadas a toda velocidad, como si explotaran.' },
  { key: 'trigger-no-salta', discipline: P, title: 'El trigger no salta', text: 'Tengo una zona que debería abrir la puerta al entrar y no pasa nada.' },
  { key: 'menu-no-responde', discipline: P, title: 'Menú que no responde', text: 'Los botones del menú de pausa no responden aunque se ven perfectamente.' },
  { key: 'salto-infinito', discipline: P, title: 'Salto infinito', text: 'Mi personaje puede saltar infinitas veces en el aire.' },
  { key: 'moneda-doble', discipline: P, title: 'Moneda que suma dos', text: 'Al recoger una moneda a veces me suma dos.' },
  { key: 'pausa-no-para', discipline: P, title: 'La pausa no para nada', text: 'Pongo pausa pero los enemigos siguen moviéndose.' },
  { key: 'escena-no-carga', discipline: P, title: 'No carga el siguiente nivel', text: 'Al terminar el nivel no carga el siguiente, se queda en negro.' },
  { key: 'boton-nada', discipline: P, title: 'Botón mudo', text: 'El botón de jugar no hace nada, ni error ni nada.' },
  { key: 'texto-no-actualiza', discipline: P, title: 'Puntuación congelada', text: 'La puntuación en pantalla no se actualiza aunque los puntos suben.' },
  { key: 'enemigo-inmortal', discipline: P, title: 'Enemigo inmortal', text: 'Le disparo al enemigo y no muere aunque la vida baja de cero.' },
  { key: 'bala-atraviesa', discipline: P, title: 'Balas que atraviesan', text: 'Las balas atraviesan a los enemigos si van rápido.' },
  { key: 'resbala', discipline: P, title: 'Resbala como en hielo', text: 'El personaje resbala al parar como si estuviera sobre hielo.' },
  { key: 'gira-al-reves', discipline: P, title: 'Gira al revés', text: 'El personaje gira hacia el ratón pero al revés.' },
  { key: 'animacion-no-cambia', discipline: P, title: 'Siempre en idle', text: 'La animación se queda en idle aunque el personaje se mueve.' },
  { key: 'sonido-no-suena-codigo', discipline: P, title: 'Sonido que no suena', text: 'Llamo a reproducir el sonido y no suena, sin errores.' },
  { key: 'guardado-no-carga', discipline: P, title: 'Carga todo a cero', text: 'Guardo la partida y al cargar aparece todo a cero.' },
  { key: 'random-igual', discipline: P, title: 'Aleatorio siempre igual', text: 'El nivel aleatorio sale siempre igual.' },
  { key: 'crash-cerrar', discipline: P, title: 'Se cuelga al cerrar', text: 'El juego se cuelga al cerrarlo.' },
  { key: 'memoria-sube', discipline: P, title: 'Memoria sin freno', text: 'La memoria sube sin parar hasta que el juego se congela.' },
  { key: 'plataforma-movil', discipline: P, title: 'Plataforma que se escapa', text: 'El personaje se queda atrás cuando va encima de una plataforma que se mueve.' },
  { key: 'esquinas', discipline: P, title: 'Enganchado en las esquinas', text: 'El personaje se engancha en las esquinas de las plataformas.' },
  { key: 'escalera', discipline: P, title: 'Escalera imposible', text: 'En las escaleras el personaje tiembla y no sube.' },
  { key: 'raycast-ciego', discipline: P, title: 'Raycast ciego', text: 'Mi raycast no detecta nada aunque hay cosas delante.' },
  { key: 'cooldown-roto', discipline: P, title: 'Cooldown que no cuenta', text: 'El cooldown del ataque no funciona, puedo atacar sin parar.' },
  { key: 'dano-multiple', discipline: P, title: 'Un golpe, varias vidas', text: 'Un solo golpe quita vida varias veces.' },
  { key: 'ui-detras', discipline: P, title: 'Botones tapados', text: 'Los botones se ven pero quedan detrás de un panel y no se pulsan.' },
  { key: 'movil-toque', discipline: P, title: 'Toques perdidos', text: 'En el móvil los toques no se detectan bien.' },
  { key: 'resolucion-camara', discipline: P, title: 'La cámara enseña de más', text: 'Al cambiar la resolución la cámara muestra más mundo del que debería.' },
  { key: 'red-desincronizada', discipline: P, title: 'Cada uno ve una cosa', text: 'En multijugador cada jugador ve a los enemigos en sitios distintos.' },
  { key: 'timer-no-para', discipline: P, title: 'Temporizador inmortal', text: 'El temporizador sigue corriendo después de morir.' },
  { key: 'objeto-no-encuentra', discipline: P, title: 'No encuentra el objeto', text: 'Me dice que no encuentra un objeto que está claramente en la escena.' },
  { key: 'error-solo-build', discipline: P, title: 'Error solo en la build', text: 'Sale un error que en el editor no pasa, solo en la build.' },
  { key: 'lento-editor', discipline: P, title: 'Lento solo en el editor', text: 'El juego va lento pero solo dentro del editor.' },

  // ---- Arte ----
  { key: 'sprites-borrosos', discipline: A, title: 'Pixel art borroso', text: 'Mis sprites de pixel art se ven borrosos dentro del juego.' },
  { key: 'modelo-rosa', discipline: A, title: 'Modelo rosa', text: 'Importé el modelo y se ve todo rosa fosforito.' },
  { key: 'normales-invertidas', discipline: A, title: 'Se ve por dentro', text: 'Mi modelo se ve por dentro pero por fuera es invisible.' },
  { key: 'escala-gigante', discipline: A, title: 'Personaje gigante', text: 'Importé el personaje y es gigante comparado con el escenario.' },
  { key: 'brazo-retorcido', discipline: A, title: 'Brazo retorcido', text: 'La animación funciona en Blender pero en el motor el brazo se retuerce.' },
  { key: 'todo-plano', discipline: A, title: 'Todo plano', text: 'Todo se ve plano y sin sombras aunque puse varias luces.' },
  { key: 'lineas-tiles', discipline: A, title: 'Líneas entre tiles', text: 'Se ven unas líneas finas entre los tiles del mapa cuando la cámara se mueve.' },
  { key: 'ui-se-sale', discipline: A, title: 'La interfaz se sale', text: 'La interfaz se ve bien en mi pantalla pero en el portátil de mi compañera se sale por los lados.' },
  { key: 'texturas-estiradas', discipline: A, title: 'Texturas estiradas', text: 'Las texturas se ven estiradas y raras en algunas caras del modelo.' },
  { key: 'sprite-cortado', discipline: A, title: 'Sprite cortado', text: 'Mi sprite aparece cortado por un lado.' },
  { key: 'sombra-rara', discipline: A, title: 'Sombra que no coincide', text: 'El personaje tiene una sombra rara que no coincide con él.' },
  { key: 'textura-negra', discipline: A, title: 'Modelo negro', text: 'El modelo se ve negro en el juego pero bien en el programa de modelado.' },
  { key: 'transparencia-blanca', discipline: A, title: 'Transparencia en blanco', text: 'Las partes transparentes de mi sprite se ven blancas.' },
  { key: 'iconos-borrosos', discipline: A, title: 'Iconos borrosos', text: 'Los iconos de la interfaz se ven borrosos.' },
  { key: 'animacion-salto-brusco', discipline: A, title: 'Salto entre animaciones', text: 'La animación da un salto al pasar de andar a correr.' },
  { key: 'luz-atraviesa', discipline: A, title: 'Luz que atraviesa', text: 'La luz atraviesa las paredes y se ve al otro lado.' },
  { key: 'colores-distintos', discipline: A, title: 'Colores cambiados', text: 'Los colores se ven distintos en el juego que en el programa de dibujo.' },
  { key: 'tiles-delante', discipline: A, title: 'Fondo por delante', text: 'Los tiles del fondo se dibujan por delante del personaje.' },
  { key: 'pierde-texturas', discipline: A, title: 'Pierde las texturas', text: 'Al exportar el modelo pierde las texturas.' },
  { key: 'codo-tubo', discipline: A, title: 'Codo de tubo', text: 'Al doblar el brazo el codo se deforma como un tubo.' },
  { key: 'particulas-cuadradas', discipline: A, title: 'Partículas cuadradas', text: 'Las partículas se ven como cuadrados negros.' },
  { key: 'fuente-no-carga', discipline: A, title: 'Fuente que no aparece', text: 'La fuente que puse no se ve, sale la de por defecto.' },
  { key: 'lod-salta', discipline: A, title: 'Cambia de forma de golpe', text: 'El modelo cambia de forma de golpe cuando me alejo.' },
  { key: 'pixel-tiembla', discipline: A, title: 'Pixel art que tiembla', text: 'El pixel art tiembla cuando la cámara se mueve.' },

  // ---- Audio ----
  { key: 'musica-se-corta', discipline: S, title: 'Música que se corta', text: 'La música se corta cada vez que cambio de escena.' },
  { key: 'sonido-retraso', discipline: S, title: 'Sonido con retraso', text: 'Los efectos de sonido suenan con retraso al pulsar el botón.' },
  { key: 'sonido-fortisimo', discipline: S, title: 'Un sonido fortísimo', text: 'Hay un sonido que suena muchísimo más fuerte que el resto y no sé por qué.' },
  { key: 'web-sin-audio', discipline: S, title: 'Web sin audio', text: 'En la versión web no suena nada hasta que haces clic en algún sitio.' },
  { key: 'loop-con-salto', discipline: S, title: 'Loop con salto', text: 'La música hace un salto raro cuando vuelve a empezar.' },
  { key: 'sonidos-solapan', discipline: S, title: 'Bola de ruido', text: 'Los sonidos se solapan y suena una bola de ruido.' },
  { key: 'volumen-no-guarda', discipline: S, title: 'Volumen que se olvida', text: 'El volumen de opciones no se guarda entre partidas.' },
  { key: 'musica-tarde', discipline: S, title: 'Música que llega tarde', text: 'La música no empieza hasta el segundo nivel.' },
  { key: 'sonido-3d-mudo', discipline: S, title: 'Sonido 3D mudo', text: 'Los sonidos 3D no se oyen aunque estoy al lado.' },
  { key: 'audio-distorsiona', discipline: S, title: 'Audio que distorsiona', text: 'El audio distorsiona cuando hay muchos sonidos a la vez.' },
  { key: 'musica-doble', discipline: S, title: 'Música con eco', text: 'La música suena dos veces a la vez, como con eco.' },
  { key: 'retraso-android', discipline: S, title: 'Retraso en Android', text: 'En Android el sonido va con retraso.' },
  { key: 'pasos-desincronizados', discipline: S, title: 'Pasos fuera de sitio', text: 'Los pasos no coinciden con la animación.' },
  { key: 'build-pesada-audio', discipline: S, title: 'Build de 400 MB', text: 'La build ocupa 400 MB por el audio.' },
  { key: 'disparo-infinito', discipline: S, title: 'Disparo que no para', text: 'El sonido de disparo no para nunca.' },

  // ---- Diseño ----
  { key: 'aburrido', discipline: D, title: 'Dicen que es aburrido', text: 'La gente que lo prueba dice que es aburrido pero no sabe decirme por qué.' },
  { key: 'demasiado-dificil', discipline: D, title: 'Nadie pasa el nivel 1', text: 'Mis amigos no pasan del primer nivel y yo lo hago sin problemas.' },
  { key: 'no-entienden', discipline: D, title: 'No saben qué hacer', text: 'Los que lo prueban no entienden qué tienen que hacer y se quedan parados.' },
  { key: 'veinte-mecanicas', discipline: D, title: 'Veinte mecánicas', text: 'Tengo 20 mecánicas pensadas y quedan 30 horas de jam.' },
  { key: 'tema-no-encaja', discipline: D, title: 'El tema no encaja', text: 'No sé cómo meter el tema de la jam en mi juego sin que quede forzado.' },
  { key: 'partidas-largas', discipline: D, title: 'Partidas eternas', text: 'Las partidas duran 40 minutos y la gente lo deja a la mitad.' },
  { key: 'muy-facil', discipline: D, title: 'Tres minutos y fin', text: 'Todo el mundo se pasa el juego en tres minutos.' },
  { key: 'tutorial-abandonan', discipline: D, title: 'Abandonan en el tutorial', text: 'La gente abandona en el tutorial.' },
  { key: 'mecanica-ignorada', discipline: D, title: 'Nadie usa la mecánica', text: 'Nadie usa la mecánica principal que diseñé.' },
  { key: 'sin-objetivo', discipline: D, title: 'Sin objetivo', text: 'Me dicen que no saben para qué juegan.' },
  { key: 'demasiado-texto', discipline: D, title: 'Demasiado texto', text: 'Me dicen que hay demasiado texto.' },
  { key: 'jefe-injusto', discipline: D, title: 'Jefe injusto', text: 'El jefe final parece injusto según los testers.' },
  { key: 'controles-raros', discipline: D, title: 'Controles raros', text: 'Todo el mundo se queja de los controles.' },
  { key: 'perdidos-nivel-2', discipline: D, title: 'Perdidos en el nivel 2', text: 'Se pierden en el segundo nivel.' },
  { key: 'economia-rota', discipline: D, title: 'Dinero de sobra', text: 'A mitad de partida tienes tanto dinero que nada importa.' },
  { key: 'principio-lento', discipline: D, title: 'Principio lento', text: 'El principio es lento y aburrido, dicen.' },
  { key: 'idea-enorme', discipline: D, title: 'Idea enorme', text: 'Tengo una idea enorme y no sé por dónde empezar.' },
  { key: 'feedback-contradictorio', discipline: D, title: 'Opiniones cruzadas', text: 'Cada tester dice una cosa distinta.' },

  // ---- Narrativa ----
  { key: 'saltan-dialogos', discipline: N, title: 'Saltan los diálogos', text: 'Tengo 40 páginas de historia y la gente se salta todos los diálogos.' },
  { key: 'final-flojo', discipline: N, title: 'Final que no emociona', text: 'El final no le emociona a nadie y no sé qué le falta.' },
  { key: 'personaje-plano', discipline: N, title: 'Protagonista plano', text: 'Dicen que mi protagonista es plano pero tiene una historia trágica enorme.' },
  { key: 'nadie-lee', discipline: N, title: 'Nadie lee los carteles', text: 'Nadie lee los carteles con la historia.' },
  { key: 'hablan-igual', discipline: N, title: 'Todos hablan igual', text: 'Dicen que todos los personajes hablan igual.' },
  { key: 'final-confuso', discipline: N, title: 'Final confuso', text: 'La gente no entiende el final.' },
  { key: 'sin-cinematicas', discipline: N, title: 'Historia sin cinemáticas', text: 'No sé cómo contar la historia sin cinemáticas.' },
  { key: 'chistes-sin-gracia', discipline: N, title: 'Chistes sin gracia', text: 'Los chistes del juego no hacen gracia a nadie.' },
  { key: 'dialogos-eternos', discipline: N, title: 'Diálogos eternos', text: 'Los diálogos se hacen eternos según los testers.' },
  { key: 'motivacion', discipline: N, title: 'Protagonista sin motivo', text: 'No sé por qué mi protagonista hace lo que hace.' },

  // ---- Producción ----
  { key: 'equipo-descoordinado', discipline: R, title: 'Cada uno por su lado', text: 'Cada uno del equipo va por su lado y al juntar las cosas no encaja nada.' },
  { key: 'seis-horas', discipline: R, title: 'Quedan seis horas', text: 'Quedan 6 horas y no tenemos ni un nivel completo. ¿Qué hacemos?' },
  { key: 'itch-no-muestra', discipline: R, title: 'itch.io no lo muestra', text: 'No consigo que la página de itch.io muestre el juego, solo sale el archivo.' },
  { key: 'crash-demo', discipline: R, title: 'Se cuelga en la demo', text: 'El juego se cuelga justo en la parte que queremos enseñar en la presentación.' },
  { key: 'no-abre-proyecto', discipline: R, title: 'No abre el proyecto', text: 'Mi compañero no puede abrir el proyecto que le pasé, a mí me abre bien.' },
  { key: 'no-llegamos', discipline: R, title: 'No llegamos', text: 'No vamos a llegar a tiempo con lo planeado.' },
  { key: 'repo-5gb', discipline: R, title: 'Repositorio de 5 GB', text: 'El repositorio pesa 5 GB y clonar tarda una hora.' },
  { key: 'compi-desaparecido', discipline: R, title: 'Compañero desaparecido', text: 'Un compañero lleva un día sin responder.' },
  { key: 'web-lenta', discipline: R, title: 'Web que tarda', text: 'La versión web tarda tres minutos en cargar.' },
  { key: 'como-testear', discipline: R, title: 'Cómo probar con gente', text: 'No sé cómo probar el juego con gente.' },
  { key: 'cambio-de-idea', discipline: R, title: 'Cambio de idea a mitad', text: 'Cambiamos de idea a mitad de jam y ahora no encaja nada.' },
  { key: 'presentacion-sin-capturas', discipline: R, title: 'Presentación sin capturas', text: 'Mañana presentamos y no tenemos ni capturas.' },
  { key: 'version-confusa', discipline: R, title: 'Cuál es la última versión', text: 'No sabemos cuál es la última versión del proyecto.' },
  { key: 'licencia-musica', discipline: R, title: 'Música de dudosa licencia', text: 'No sé si puedo usar esta música que encontré.' },
  { key: 'cuello-de-botella', discipline: R, title: 'Todo pasa por mí', text: 'Soy el único que programa y todo pasa por mí.' },
];
