/**
 * Términos de "Mata la jerga". Hay que explicar `term` sin usar ninguna de las
 * palabras `banned` (ni el propio término). La comprobación ignora mayúsculas, acentos y plurales simples.
 * Usa palabras prohibidas cortas y comunes: la gracia es obligar a explicar en lenguaje llano.
 */
module.exports = [
  // ---- Programación: conceptos básicos ----
  { term: 'Variable', banned: ['guardar', 'valor', 'nombre', 'dato', 'caja'] },
  { term: 'Array', banned: ['lista', 'elementos', 'índice', 'colección', 'posición'] },
  { term: 'Diccionario', banned: ['clave', 'valor', 'buscar', 'pares', 'lista'] },
  { term: 'Enum', banned: ['lista', 'opciones', 'constantes', 'valores', 'nombres'] },
  { term: 'Bucle (loop)', banned: ['repetir', 'veces', 'iterar', 'while', 'for'] },
  { term: 'Recursión', banned: ['función', 'llamarse', 'misma', 'repetir', 'bucle'] },
  { term: 'Herencia', banned: ['clase', 'padre', 'hijo', 'heredar', 'extender'] },
  { term: 'Interfaz (programación)', banned: ['contrato', 'métodos', 'implementar', 'clase', 'promesa'] },
  { term: 'Null', banned: ['nada', 'vacío', 'referencia', 'error', 'objeto'] },
  { term: 'Excepción', banned: ['error', 'fallo', 'capturar', 'try', 'lanzar'] },
  { term: 'Máquina de estados', banned: ['comportamiento', 'transición', 'condición', 'cambiar', 'enum'] },
  { term: 'Singleton', banned: ['instancia', 'única', 'global', 'clase', 'acceso'] },
  { term: 'Evento (event)', banned: ['avisar', 'suscribir', 'ocurre', 'llamar', 'escuchar'] },
  { term: 'Observer (patrón)', banned: ['avisar', 'suscribir', 'cambio', 'escuchar', 'notificar'] },
  { term: 'Corrutina', banned: ['esperar', 'pausar', 'función', 'tiempo', 'hilo'] },
  { term: 'Interpolación (lerp)', banned: ['entre', 'valor', 'suave', 'porcentaje', 'transición'] },
  { term: 'Delta time', banned: ['tiempo', 'frame', 'fotograma', 'velocidad', 'segundos'] },
  { term: 'Frame rate (FPS)', banned: ['fotogramas', 'segundo', 'velocidad', 'fluido', 'rendimiento'] },
  { term: 'Serialización', banned: ['guardar', 'datos', 'archivo', 'convertir', 'texto'] },
  { term: 'Semilla (seed)', banned: ['aleatorio', 'número', 'mismo', 'generar', 'repetir'] },
  { term: 'API', banned: ['funciones', 'usar', 'biblioteca', 'llamar', 'código'] },
  { term: 'Plugin', banned: ['añadir', 'extensión', 'herramienta', 'motor', 'función'] },

  // ---- Programación: motor y arquitectura ----
  { term: 'Motor (engine)', banned: ['Unity', 'Godot', 'herramienta', 'programa', 'crear'] },
  { term: 'Componente', banned: ['pieza', 'objeto', 'añadir', 'comportamiento', 'script'] },
  { term: 'Prefab', banned: ['plantilla', 'copia', 'objeto', 'reutilizar', 'instancia'] },
  { term: 'Scriptable Object', banned: ['datos', 'archivo', 'configuración', 'asset', 'clase'] },
  { term: 'Transform', banned: ['posición', 'rotación', 'escala', 'objeto', 'mover'] },
  { term: 'Espacio local vs mundial', banned: ['coordenadas', 'padre', 'origen', 'posición', 'relativo'] },
  { term: 'Rigidbody', banned: ['física', 'gravedad', 'fuerzas', 'masa', 'componente'] },
  { term: 'Collider', banned: ['chocar', 'física', 'forma', 'cuerpo', 'tocar'] },
  { term: 'Trigger (zona)', banned: ['colisión', 'entrar', 'evento', 'detectar', 'atravesar'] },
  { term: 'Raycast', banned: ['rayo', 'línea', 'colisión', 'dirección', 'detectar'] },
  { term: 'Hitbox', banned: ['golpe', 'zona', 'daño', 'colisión', 'ataque'] },
  { term: 'Quaternion', banned: ['rotación', 'ángulo', 'eje', 'giro', 'euler'] },
  { term: 'Tilemap', banned: ['cuadrícula', 'celda', 'mosaico', 'mapa', 'nivel'] },
  { term: 'Object pooling', banned: ['reutilizar', 'instanciar', 'destruir', 'memoria', 'lista'] },
  { term: 'Garbage collector', banned: ['memoria', 'liberar', 'basura', 'objetos', 'automático'] },
  { term: 'Guardado (save system)', banned: ['partida', 'archivo', 'progreso', 'cargar', 'datos'] },
  { term: 'Localización (i18n)', banned: ['idiomas', 'traducir', 'textos', 'países', 'cambiar'] },
  { term: 'Input', banned: ['teclado', 'mando', 'pulsar', 'botón', 'jugador'] },
  { term: 'Input buffering', banned: ['pulsar', 'antes', 'recordar', 'botón', 'tiempo'] },
  { term: 'Coyote time', banned: ['saltar', 'borde', 'tarde', 'plataforma', 'tiempo'] },
  { term: 'Frame data', banned: ['fotogramas', 'ataque', 'golpe', 'tiempo', 'recuperación'] },
  { term: 'Smooth follow (cámara)', banned: ['seguir', 'personaje', 'suave', 'movimiento', 'brusco'] },
  { term: 'Parallax', banned: ['fondo', 'capas', 'velocidad', 'profundidad', 'mover'] },

  // ---- Programación: IA, red y procedural ----
  { term: 'IA (inteligencia artificial)', banned: ['enemigos', 'comportamiento', 'decidir', 'inteligente', 'cerebro'] },
  { term: 'Behaviour tree', banned: ['árbol', 'decisiones', 'IA', 'ramas', 'comportamiento'] },
  { term: 'Pathfinding', banned: ['camino', 'ruta', 'enemigo', 'llegar', 'obstáculos'] },
  { term: 'NavMesh', banned: ['camino', 'caminar', 'superficie', 'navegar', 'IA'] },
  { term: 'Generación procedural', banned: ['aleatorio', 'algoritmo', 'crear', 'contenido', 'niveles'] },
  { term: 'Ruido Perlin', banned: ['aleatorio', 'suave', 'terreno', 'generar', 'ondas'] },
  { term: 'Multijugador', banned: ['jugadores', 'red', 'conectar', 'online', 'juntos'] },
  { term: 'Latencia (lag)', banned: ['retraso', 'red', 'tiempo', 'lento', 'servidor'] },
  { term: 'Sincronización', banned: ['mismo', 'estado', 'jugadores', 'red', 'tiempo'] },

  // ---- Programación: rendimiento y calidad ----
  { term: 'Bug', banned: ['error', 'fallo', 'comportamiento', 'esperado', 'arreglar'] },
  { term: 'Debug', banned: ['error', 'encontrar', 'arreglar', 'consola', 'fallo'] },
  { term: 'Breakpoint', banned: ['pausar', 'depurar', 'línea', 'ejecución', 'inspeccionar'] },
  { term: 'Refactorizar', banned: ['código', 'mejorar', 'limpiar', 'cambiar', 'funcionalidad'] },
  { term: 'Código espagueti', banned: ['desordenado', 'enredado', 'líneas', 'difícil', 'entender'] },
  { term: 'Deuda técnica', banned: ['atajos', 'código', 'después', 'arreglar', 'prisa'] },
  { term: 'Optimización', banned: ['rápido', 'rendimiento', 'mejorar', 'recursos', 'lento'] },
  { term: 'Profiler', banned: ['rendimiento', 'medir', 'lento', 'tiempo', 'herramienta'] },
  { term: 'Culling', banned: ['dibujar', 'cámara', 'fuera', 'ocultar', 'rendimiento'] },
  { term: 'Draw call', banned: ['dibujar', 'GPU', 'orden', 'objeto', 'rendimiento'] },
  { term: 'Batching', banned: ['agrupar', 'dibujar', 'llamadas', 'rendimiento', 'GPU'] },
  { term: 'Hotfix', banned: ['arreglo', 'rápido', 'urgente', 'parche', 'lanzar'] },

  // ---- Matemáticas ----
  { term: 'Vector', banned: ['dirección', 'flecha', 'magnitud', 'posición', 'coordenadas'] },
  { term: 'Vector unitario', banned: ['longitud', 'uno', 'dirección', 'tamaño', 'normalizar'] },
  { term: 'Producto escalar (dot)', banned: ['vectores', 'ángulo', 'multiplicar', 'dirección', 'número'] },
  { term: 'Curva Bézier', banned: ['puntos', 'suave', 'control', 'línea', 'trayectoria'] },

  // ---- Arte 2D ----
  { term: 'Sprite', banned: ['imagen', 'dibujo', 'personaje', '2D', 'animación'] },
  { term: 'Sprite sheet', banned: ['imagen', 'fotogramas', 'animación', 'cuadrícula', 'archivo'] },
  { term: 'Pixel art', banned: ['pequeño', 'cuadrado', 'resolución', 'dibujo', 'retro'] },
  { term: 'Paleta', banned: ['colores', 'limitada', 'conjunto', 'tonos', 'elegir'] },
  { term: 'Dithering', banned: ['puntos', 'colores', 'mezclar', 'degradado', 'patrón'] },
  { term: 'Silueta', banned: ['forma', 'contorno', 'negro', 'reconocer', 'personaje'] },
  { term: 'Outline', banned: ['borde', 'contorno', 'línea', 'personaje', 'destacar'] },
  { term: 'Tileset', banned: ['piezas', 'cuadrícula', 'mapa', 'suelo', 'combinar'] },
  { term: 'Atlas de texturas', banned: ['imagen', 'sprites', 'juntar', 'memoria', 'archivo'] },
  { term: 'Alpha (transparencia)', banned: ['transparente', 'canal', 'ver', 'través', 'opaco'] },
  { term: 'Nine-slice', banned: ['bordes', 'estirar', 'imagen', 'esquinas', 'botón'] },
  { term: 'Concept art', banned: ['dibujo', 'idea', 'diseño', 'antes', 'boceto'] },
  { term: 'Moodboard', banned: ['imágenes', 'referencias', 'estilo', 'inspiración', 'collage'] },
  { term: 'Guía de estilo', banned: ['reglas', 'colores', 'consistente', 'documento', 'aspecto'] },

  // ---- Arte 3D ----
  { term: 'Mesh (malla)', banned: ['vértices', 'polígonos', 'forma', 'modelo', 'triángulos'] },
  { term: 'Polígono', banned: ['triángulo', 'cara', 'malla', 'modelo', 'forma'] },
  { term: 'Low poly', banned: ['pocos', 'polígonos', 'sencillo', 'estilo', 'triángulos'] },
  { term: 'High poly', banned: ['muchos', 'polígonos', 'detalle', 'esculpir', 'pesado'] },
  { term: 'Esculpir', banned: ['arcilla', 'modelo', 'detalle', 'pincel', 'orgánico'] },
  { term: 'Retopología', banned: ['malla', 'polígonos', 'rehacer', 'limpia', 'animar'] },
  { term: 'UV', banned: ['textura', 'mapa', 'coordenadas', 'desplegar', 'modelo'] },
  { term: 'Texel density', banned: ['textura', 'píxeles', 'tamaño', 'uniforme', 'resolución'] },
  { term: 'Material', banned: ['textura', 'superficie', 'brillo', 'color', 'aspecto'] },
  { term: 'PBR', banned: ['realista', 'luz', 'materiales', 'físico', 'metal'] },
  { term: 'Normal map', banned: ['relieve', 'textura', 'luz', 'detalle', 'superficie'] },
  { term: 'Bake (horneado)', banned: ['guardar', 'textura', 'calcular', 'luz', 'detalle'] },
  { term: 'Ambient occlusion', banned: ['sombra', 'esquinas', 'luz', 'oscuro', 'contacto'] },
  { term: 'Lightmap', banned: ['luz', 'textura', 'guardar', 'sombras', 'estático'] },
  { term: 'Skybox', banned: ['cielo', 'fondo', 'cubo', 'lejos', 'imagen'] },
  { term: 'LOD', banned: ['distancia', 'detalle', 'polígonos', 'lejos', 'rendimiento'] },
  { term: 'Mipmap', banned: ['textura', 'versiones', 'pequeñas', 'distancia', 'resolución'] },
  { term: 'Tiling', banned: ['repetir', 'textura', 'patrón', 'bordes', 'seamless'] },
  { term: 'Seamless', banned: ['bordes', 'repetir', 'textura', 'unión', 'notar'] },
  { term: 'Pivot', banned: ['punto', 'centro', 'rotar', 'origen', 'objeto'] },
  { term: 'Kitbash', banned: ['piezas', 'juntar', 'reutilizar', 'modelos', 'rápido'] },
  { term: 'Modular', banned: ['piezas', 'combinar', 'reutilizar', 'encajar', 'construir'] },
  { term: 'Shader', banned: ['luz', 'color', 'GPU', 'material', 'programa'] },
  { term: 'Cel shading', banned: ['dibujo', 'animado', 'sombras', 'planas', 'contorno'] },
  { term: 'Post-procesado', banned: ['efectos', 'imagen', 'final', 'filtro', 'pantalla'] },
  { term: 'Bloom', banned: ['brillo', 'luz', 'resplandor', 'efecto', 'desbordar'] },
  { term: 'Partículas', banned: ['efectos', 'pequeñas', 'fuego', 'humo', 'muchas'] },
  { term: 'VFX', banned: ['efectos', 'visuales', 'partículas', 'explosión', 'magia'] },

  // ---- Animación ----
  { term: 'Rig', banned: ['huesos', 'esqueleto', 'animar', 'personaje', 'deformar'] },
  { term: 'Animación esquelética', banned: ['huesos', 'rig', 'mover', 'personaje', 'deformar'] },
  { term: 'Animación por fotogramas', banned: ['dibujos', 'seguidos', 'imágenes', 'movimiento', 'secuencia'] },
  { term: 'Keyframe', banned: ['posición', 'momento', 'animación', 'entre', 'clave'] },
  { term: 'Tweening', banned: ['entre', 'suave', 'animación', 'valores', 'automático'] },
  { term: 'Easing', banned: ['suave', 'acelerar', 'frenar', 'animación', 'curva'] },
  { term: 'Blend tree', banned: ['mezclar', 'animaciones', 'velocidad', 'transición', 'parámetro'] },
  { term: 'Squash and stretch', banned: ['aplastar', 'estirar', 'animación', 'peso', 'vivo'] },
  { term: 'Anticipación (animación)', banned: ['antes', 'movimiento', 'preparar', 'avisar', 'salto'] },

  // ---- Interfaz ----
  { term: 'UI', banned: ['botones', 'menús', 'pantalla', 'interfaz', 'jugador'] },
  { term: 'HUD', banned: ['pantalla', 'información', 'vida', 'interfaz', 'jugador'] },
  { term: 'Wireframe', banned: ['boceto', 'pantalla', 'cajas', 'diseño', 'estructura'] },
  { term: 'Anchors (UI)', banned: ['pantalla', 'esquina', 'posición', 'tamaño', 'resolución'] },
  { term: 'Diegético (UI)', banned: ['dentro', 'mundo', 'interfaz', 'personaje', 'ver'] },
  { term: 'Accesibilidad', banned: ['todos', 'jugar', 'opciones', 'discapacidad', 'adaptar'] },
  { term: 'Remapeo de controles', banned: ['teclas', 'cambiar', 'botones', 'asignar', 'jugador'] },

  // ---- Audio ----
  { term: 'SFX', banned: ['efectos', 'sonido', 'golpe', 'corto', 'acción'] },
  { term: 'BGM', banned: ['música', 'fondo', 'escuchar', 'ambiente', 'canción'] },
  { term: 'Chiptune', banned: ['8 bits', 'retro', 'consola', 'sonido', 'música'] },
  { term: 'Loop de audio', banned: ['repetir', 'música', 'bucle', 'cortes', 'fondo'] },
  { term: 'Sample (muestra)', banned: ['grabación', 'trozo', 'sonido', 'reutilizar', 'archivo'] },
  { term: 'DAW', banned: ['programa', 'música', 'grabar', 'pistas', 'editar'] },
  { term: 'Sintetizador', banned: ['instrumento', 'sonido', 'electrónico', 'ondas', 'crear'] },
  { term: 'Mezcla (mix)', banned: ['volumen', 'pistas', 'equilibrar', 'sonidos', 'niveles'] },
  { term: 'Reverb', banned: ['eco', 'espacio', 'sala', 'rebotar', 'grande'] },
  { term: 'Compresor', banned: ['volumen', 'fuerte', 'bajo', 'igualar', 'dinámica'] },
  { term: 'Ecualizador', banned: ['frecuencias', 'graves', 'agudos', 'ajustar', 'sonido'] },
  { term: 'Normalizar (audio)', banned: ['volumen', 'máximo', 'subir', 'igual', 'nivel'] },
  { term: 'Clipping (audio)', banned: ['distorsión', 'volumen', 'máximo', 'rojo', 'romper'] },
  { term: 'Ducking', banned: ['bajar', 'volumen', 'música', 'diálogo', 'prioridad'] },
  { term: 'Foley', banned: ['efectos', 'grabar', 'objetos', 'sonido', 'realista'] },
  { term: 'Stinger', banned: ['corto', 'musical', 'momento', 'aviso', 'golpe'] },
  { term: 'Audio espacial', banned: ['dirección', 'distancia', 'lejos', 'izquierda', 'derecha'] },
  { term: 'Variación de tono (pitch)', banned: ['agudo', 'repetir', 'mismo', 'cambiar', 'cansar'] },
  { term: 'Tempo (BPM)', banned: ['velocidad', 'ritmo', 'rápido', 'lento', 'pulsos'] },
  { term: 'Leitmotiv', banned: ['melodía', 'personaje', 'repetir', 'tema', 'reconocer'] },
  { term: 'Música adaptativa', banned: ['cambiar', 'situación', 'capas', 'intensidad', 'jugador'] },
  { term: 'Pasos (footsteps)', banned: ['caminar', 'superficie', 'sonido', 'pies', 'material'] },
  { term: 'Doblaje (voces)', banned: ['actor', 'grabar', 'personaje', 'hablar', 'diálogo'] },

  // ---- Diseño ----
  { term: 'Mecánica', banned: ['regla', 'acción', 'jugador', 'hacer', 'sistema'] },
  { term: 'Dinámica', banned: ['mecánicas', 'jugador', 'surge', 'comportamiento', 'interacción'] },
  { term: 'Estética (MDA)', banned: ['emoción', 'sentir', 'jugador', 'experiencia', 'diversión'] },
  { term: 'Core loop', banned: ['bucle', 'repetir', 'acciones', 'principal', 'ciclo'] },
  { term: 'Game feel (juice)', banned: ['sensación', 'partículas', 'vibración', 'respuesta', 'satisfactorio'] },
  { term: 'Bucle de feedback', banned: ['respuesta', 'acción', 'jugador', 'ver', 'consecuencia'] },
  { term: 'Bola de nieve (snowball)', banned: ['ganar', 'ventaja', 'más', 'crecer', 'imparable'] },
  { term: 'Rubber banding', banned: ['ayudar', 'perder', 'igualar', 'atrás', 'carrera'] },
  { term: 'Prototipo', banned: ['rápido', 'probar', 'idea', 'feo', 'funcionar'] },
  { term: 'Paper prototype', banned: ['papel', 'probar', 'idea', 'rápido', 'mesa'] },
  { term: 'Greybox', banned: ['cubos', 'nivel', 'probar', 'sin', 'arte'] },
  { term: 'Placeholder', banned: ['temporal', 'provisional', 'sustituir', 'cubo', 'final'] },
  { term: 'Level design', banned: ['nivel', 'espacio', 'jugador', 'colocar', 'recorrido'] },
  { term: 'Señalización (signposting)', banned: ['guiar', 'camino', 'jugador', 'indicar', 'perderse'] },
  { term: 'Affordance', banned: ['indicar', 'intuitivo', 'forma', 'usar', 'evidente'] },
  { term: 'Pacing', banned: ['ritmo', 'tensión', 'descanso', 'momentos', 'velocidad'] },
  { term: 'Flow', banned: ['concentración', 'reto', 'habilidad', 'tiempo', 'absorto'] },
  { term: 'Agencia', banned: ['decisiones', 'jugador', 'control', 'importar', 'elegir'] },
  { term: 'Emergencia', banned: ['sistemas', 'inesperado', 'combinar', 'surge', 'planeado'] },
  { term: 'Curva de dificultad', banned: ['difícil', 'fácil', 'progresión', 'nivel', 'jugador'] },
  { term: 'Progresión', banned: ['avanzar', 'mejorar', 'niveles', 'desbloquear', 'jugador'] },
  { term: 'Balanceo', banned: ['equilibrar', 'fuerte', 'débil', 'ajustar', 'números'] },
  { term: 'Economía (in-game)', banned: ['monedas', 'recursos', 'gastar', 'ganar', 'precio'] },
  { term: 'Grind', banned: ['repetir', 'aburrido', 'subir', 'tiempo', 'recompensa'] },
  { term: 'Riesgo-recompensa', banned: ['peligro', 'premio', 'decidir', 'arriesgar', 'ganar'] },
  { term: 'Loot', banned: ['botín', 'objetos', 'recoger', 'enemigos', 'recompensa'] },
  { term: 'Crafteo', banned: ['combinar', 'materiales', 'crear', 'objetos', 'recetas'] },
  { term: 'Cooldown', banned: ['esperar', 'tiempo', 'habilidad', 'usar', 'volver'] },
  { term: 'Buff / Debuff', banned: ['mejorar', 'empeorar', 'temporal', 'personaje', 'estadísticas'] },
  { term: 'Stats (estadísticas)', banned: ['números', 'fuerza', 'vida', 'personaje', 'atributos'] },
  { term: 'RNG', banned: ['aleatorio', 'suerte', 'azar', 'números', 'dados'] },
  { term: 'Checkpoint', banned: ['guardar', 'punto', 'morir', 'volver', 'progreso'] },
  { term: 'Permadeath', banned: ['morir', 'perder', 'todo', 'empezar', 'definitivo'] },
  { term: 'Roguelike', banned: ['aleatorio', 'morir', 'empezar', 'niveles', 'mazmorra'] },
  { term: 'Metajuego', banned: ['fuera', 'partida', 'estrategia', 'comunidad', 'jugar'] },
  { term: 'Sandbox', banned: ['libertad', 'jugar', 'reglas', 'crear', 'objetivo'] },
  { term: 'Condición de victoria', banned: ['ganar', 'objetivo', 'terminar', 'cumplir', 'jugador'] },
  { term: 'Fail state', banned: ['perder', 'morir', 'terminar', 'fallo', 'game over'] },
  { term: 'Tutorial', banned: ['enseñar', 'aprender', 'principio', 'controles', 'jugador'] },
  { term: 'Playtest', banned: ['probar', 'jugadores', 'feedback', 'observar', 'opiniones'] },
  { term: 'MVP', banned: ['mínimo', 'producto', 'viable', 'básico', 'primero'] },
  { term: 'Scope creep', banned: ['alcance', 'añadir', 'funciones', 'tiempo', 'crecer'] },
  { term: 'Kill your darlings', banned: ['quitar', 'idea', 'favorita', 'eliminar', 'mejor'] },

  // ---- Narrativa ----
  { term: 'Worldbuilding', banned: ['mundo', 'historia', 'crear', 'lore', 'universo'] },
  { term: 'Lore', banned: ['historia', 'mundo', 'fondo', 'detalles', 'universo'] },
  { term: 'Narrativa ambiental', banned: ['entorno', 'contar', 'escenario', 'objetos', 'diálogo'] },
  { term: 'Disonancia ludonarrativa', banned: ['historia', 'mecánicas', 'contradicción', 'jugabilidad', 'personaje'] },
  { term: 'Diálogo ramificado', banned: ['opciones', 'elegir', 'conversación', 'caminos', 'consecuencias'] },
  { term: 'Arco de personaje', banned: ['cambio', 'evolución', 'historia', 'principio', 'final'] },
  { term: 'Protagonista', banned: ['personaje', 'principal', 'héroe', 'historia', 'jugador'] },
  { term: 'Antagonista', banned: ['villano', 'enemigo', 'malo', 'oponerse', 'protagonista'] },
  { term: 'NPC', banned: ['personaje', 'controlado', 'jugador', 'hablar', 'ordenador'] },
  { term: 'Bark', banned: ['frase', 'corta', 'personaje', 'decir', 'repetir'] },
  { term: 'Mostrar, no contar', banned: ['explicar', 'ver', 'decir', 'acción', 'escena'] },
  { term: 'Exposición', banned: ['explicar', 'información', 'historia', 'contar', 'mundo'] },
  { term: 'Giro de guion', banned: ['sorpresa', 'inesperado', 'historia', 'cambio', 'final'] },
  { term: 'Foreshadowing', banned: ['pista', 'antes', 'adelantar', 'futuro', 'sorpresa'] },
  { term: 'Estructura en tres actos', banned: ['principio', 'medio', 'final', 'partes', 'historia'] },
  { term: 'Viaje del héroe', banned: ['aventura', 'llamada', 'volver', 'cambio', 'estructura'] },
  { term: 'Voz del personaje', banned: ['hablar', 'forma', 'reconocer', 'diálogo', 'personalidad'] },
  { term: 'Tono', banned: ['sensación', 'serio', 'divertido', 'ambiente', 'estilo'] },
  { term: 'Ritmo narrativo', banned: ['velocidad', 'historia', 'escenas', 'tensión', 'lento'] },
  { term: 'Tema (narrativo)', banned: ['mensaje', 'idea', 'historia', 'fondo', 'significado'] },
  { term: 'Codex / glosario', banned: ['textos', 'información', 'coleccionar', 'leer', 'mundo'] },
  { term: 'Cinemática', banned: ['vídeo', 'escena', 'ver', 'historia', 'control'] },
  { term: 'Quest', banned: ['misión', 'objetivo', 'tarea', 'recompensa', 'completar'] },

  // ---- Producción ----
  { term: 'Roadmap', banned: ['plan', 'futuro', 'fechas', 'objetivos', 'camino'] },
  { term: 'Backlog', banned: ['lista', 'tareas', 'pendientes', 'hacer', 'prioridad'] },
  { term: 'Sprint', banned: ['semanas', 'tareas', 'periodo', 'corto', 'objetivo'] },
  { term: 'Daily standup', banned: ['reunión', 'corta', 'cada', 'día', 'equipo'] },
  { term: 'Kanban', banned: ['tablero', 'tarjetas', 'columnas', 'tareas', 'mover'] },
  { term: 'Hito (milestone)', banned: ['objetivo', 'fecha', 'entrega', 'plan', 'etapa'] },
  { term: 'Deadline', banned: ['fecha', 'entrega', 'límite', 'tiempo', 'terminar'] },
  { term: 'Time boxing', banned: ['tiempo', 'límite', 'tarea', 'fijo', 'parar'] },
  { term: 'Pipeline', banned: ['pasos', 'proceso', 'orden', 'herramientas', 'flujo'] },
  { term: 'Vertical slice', banned: ['trozo', 'completo', 'pequeño', 'calidad', 'final'] },
  { term: 'Alpha (versión)', banned: ['incompleta', 'funciones', 'probar', 'temprana', 'primera'] },
  { term: 'Beta', banned: ['versión', 'probar', 'casi', 'terminada', 'errores'] },
  { term: 'Gold master', banned: ['versión', 'final', 'terminada', 'lanzar', 'enviar'] },
  { term: 'Build', banned: ['compilar', 'exportar', 'ejecutable', 'versión', 'subir'] },
  { term: 'WebGL build', banned: ['navegador', 'jugar', 'HTML5', 'exportar', 'descargar'] },
  { term: 'QA', banned: ['probar', 'errores', 'calidad', 'encontrar', 'reportar'] },
  { term: 'Postmortem', banned: ['después', 'análisis', 'salió', 'aprender', 'jam'] },
  { term: 'Crunch', banned: ['horas', 'dormir', 'trabajo', 'presión', 'fecha'] },
  { term: 'Burnout', banned: ['cansancio', 'agotamiento', 'trabajo', 'descansar', 'estrés'] },
  { term: 'Devlog', banned: ['contar', 'progreso', 'publicar', 'desarrollo', 'escribir'] },
  { term: 'Pitch', banned: ['contar', 'idea', 'corto', 'convencer', 'juego'] },
  { term: 'Trailer', banned: ['vídeo', 'corto', 'mostrar', 'juego', 'promocionar'] },
  { term: 'Página de itch.io', banned: ['subir', 'publicar', 'web', 'juego', 'descargar'] },

  // ---- Control de versiones ----
  { term: 'Control de versiones', banned: ['git', 'cambios', 'historial', 'commit', 'guardar'] },
  { term: 'Repositorio', banned: ['código', 'guardar', 'proyecto', 'historial', 'nube'] },
  { term: 'Commit', banned: ['guardar', 'cambios', 'mensaje', 'historial', 'punto'] },
  { term: 'Branch', banned: ['rama', 'copia', 'trabajar', 'cambios', 'separado'] },
  { term: 'Merge conflict', banned: ['cambios', 'mismo', 'archivo', 'chocar', 'resolver'] },
  { term: 'Pull request', banned: ['cambios', 'revisar', 'unir', 'rama', 'aprobar'] },
  { term: 'Fork (git)', banned: ['copia', 'repositorio', 'propia', 'cambios', 'original'] },
  { term: '.gitignore', banned: ['archivos', 'ignorar', 'subir', 'secretos', 'lista'] },

  // ---- Cultura de jam ----
  { term: 'Game jam', banned: ['tiempo', 'horas', 'evento', 'crear', 'equipo'] },
  { term: 'Tema de la jam', banned: ['palabra', 'idea', 'inspiración', 'obligatorio', 'anunciar'] },
  { term: 'Ludum Dare', banned: ['jam', 'famosa', 'horas', 'evento', 'tema'] },
  { term: 'Global Game Jam', banned: ['mundial', 'evento', 'sitios', 'fin de semana', 'enero'] },
  { term: 'Solo dev', banned: ['persona', 'sola', 'todo', 'equipo', 'hacer'] },
  { term: 'Rating de la jam', banned: ['puntuar', 'juegos', 'estrellas', 'categorías', 'otros'] },
  { term: 'Versión post-jam', banned: ['después', 'arreglar', 'mejorar', 'subir', 'errores'] },
];
