/**
 * Cosas que necesitan nombre, para Nómbralo.
 *
 * Cada entrada:
 *   key     - identificador estable (se usa para no repetir casos recientes)
 *   kind    - qué es: variable, constante, función, método, clase, componente, escena, asset, evento, señal, enum, capa, etiqueta...
 *   what    - qué representa, en pocas palabras
 *   context - detalle que ayuda a elegir bien el nombre (opcional)
 */
module.exports = [
  // ---- Variables ----
  { key: 'vida-actual', kind: 'una variable', what: 'la vida que le queda al jugador ahora mismo', context: 'Cambia durante la partida; hay otra variable con el máximo.' },
  { key: 'vida-maxima', kind: 'una variable', what: 'la vida máxima del jugador', context: 'Solo cambia al subir de nivel.' },
  { key: 'puede-saltar', kind: 'una variable', what: 'si el personaje puede saltar en este momento', context: 'Es verdadero o falso y se comprueba cada fotograma.' },
  { key: 'esta-en-suelo', kind: 'una variable', what: 'si el personaje está tocando el suelo', context: 'Se actualiza en cada paso de física.' },
  { key: 'es-invulnerable', kind: 'una variable', what: 'si el jugador ignora el daño ahora mismo', context: 'Se activa unos instantes tras recibir un golpe.' },
  { key: 'esta-pausado', kind: 'una variable', what: 'si el juego está en pausa' },
  { key: 'lista-enemigos', kind: 'una variable', what: 'todos los enemigos vivos en la escena', context: 'Se añaden y se quitan constantemente.' },
  { key: 'temporizador-oleada', kind: 'una variable', what: 'los segundos que faltan para la siguiente oleada' },
  { key: 'multiplicador-puntos', kind: 'una variable', what: 'por cuánto se multiplican los puntos ahora mismo', context: 'Sube con el combo y vuelve a 1 al fallar.' },
  { key: 'semilla-partida', kind: 'una variable', what: 'la semilla con la que se generó esta partida' },
  { key: 'puntos-aparicion', kind: 'una variable', what: 'los lugares donde pueden aparecer enemigos' },
  { key: 'ultimo-checkpoint', kind: 'una variable', what: 'la posición del último punto de control alcanzado' },
  { key: 'dialogo-actual', kind: 'una variable', what: 'la línea de diálogo que se está mostrando ahora' },
  { key: 'cola-mensajes', kind: 'una variable', what: 'los mensajes pendientes de mostrar en pantalla, en orden' },
  { key: 'objetivo-camara', kind: 'una variable', what: 'el objeto al que sigue la cámara' },
  { key: 'mapa-teclas', kind: 'una variable', what: 'qué tecla corresponde a cada acción' },
  { key: 'monedas', kind: 'una variable', what: 'cuántas monedas tiene el jugador' },
  { key: 'nivel-actual', kind: 'una variable', what: 'el número del nivel en el que está el jugador' },
  { key: 'tiempo-partida', kind: 'una variable', what: 'los segundos que lleva la partida en marcha' },
  { key: 'combo-actual', kind: 'una variable', what: 'el número de golpes seguidos sin fallar' },
  { key: 'municion-cargador', kind: 'una variable', what: 'las balas que quedan en el cargador', context: 'Hay otra variable con las balas de reserva.' },
  { key: 'municion-reserva', kind: 'una variable', what: 'las balas de reserva fuera del cargador' },
  { key: 'objetivo-torreta', kind: 'una variable', what: 'el enemigo al que apunta la torreta ahora mismo', context: 'Puede no haber ninguno.' },
  { key: 'direccion-mirada', kind: 'una variable', what: 'hacia dónde mira el personaje: izquierda o derecha' },
  { key: 'esta-agachado', kind: 'una variable', what: 'si el personaje está agachado' },
  { key: 'esta-muerto', kind: 'una variable', what: 'si el enemigo ya ha muerto y espera a desaparecer' },
  { key: 'velocidad-actual', kind: 'una variable', what: 'la velocidad a la que se mueve el personaje ahora mismo', context: 'Cambia al correr o al frenar.' },
  { key: 'ultimo-ataque', kind: 'una variable', what: 'el instante en que se hizo el último ataque' },
  { key: 'nivel-max-desbloqueado', kind: 'una variable', what: 'el nivel más alto que se ha desbloqueado' },
  { key: 'idioma-actual', kind: 'una variable', what: 'el idioma elegido en opciones' },
  { key: 'sala-actual', kind: 'una variable', what: 'la sala de la mazmorra en la que está el jugador' },
  { key: 'salas-visitadas', kind: 'una variable', what: 'las salas que ya se han visitado' },
  { key: 'jugadores-conectados', kind: 'una variable', what: 'quiénes están conectados a la partida' },
  { key: 'oleada-actual', kind: 'una variable', what: 'el número de la oleada que está en curso' },
  { key: 'esta-cargando', kind: 'una variable', what: 'si se está cargando una escena ahora mismo' },
  { key: 'dialogo-abierto', kind: 'una variable', what: 'si hay una conversación en pantalla' },
  { key: 'puntos-partida', kind: 'una variable', what: 'los puntos conseguidos solo en esta partida', context: 'Hay otra variable con el total histórico.' },
  { key: 'mejor-tiempo', kind: 'una variable', what: 'el mejor tiempo conseguido en el nivel' },

  // ---- Constantes ----
  { key: 'tiempo-coyote', kind: 'una constante', what: 'los segundos en que aún se puede saltar tras dejar el borde', context: 'No cambia nunca durante la partida.' },
  { key: 'velocidad-maxima', kind: 'una constante', what: 'la velocidad máxima horizontal del personaje' },
  { key: 'fuerza-salto', kind: 'una constante', what: 'el impulso vertical inicial del salto' },
  { key: 'duracion-invulnerable', kind: 'una constante', what: 'cuántos segundos dura la invulnerabilidad tras un golpe' },
  { key: 'suavizado-camara', kind: 'una constante', what: 'cuánto tarda la cámara en alcanzar su objetivo' },
  { key: 'gravedad', kind: 'una constante', what: 'la aceleración hacia abajo que sufren los personajes' },
  { key: 'max-inventario', kind: 'una constante', what: 'cuántos objetos caben como máximo en el inventario' },
  { key: 'radio-deteccion', kind: 'una constante', what: 'a qué distancia el enemigo empieza a ver al jugador' },
  { key: 'tiempo-respawn', kind: 'una constante', what: 'cuántos segundos tarda el jugador en reaparecer' },
  { key: 'vidas-iniciales', kind: 'una constante', what: 'con cuántas vidas se empieza' },
  { key: 'capacidad-cargador', kind: 'una constante', what: 'cuántas balas caben en el cargador' },
  { key: 'buffer-salto', kind: 'una constante', what: 'durante cuántos segundos se recuerda una pulsación de salto' },
  { key: 'tamano-tile', kind: 'una constante', what: 'cuántos píxeles mide un tile' },
  { key: 'max-jugadores', kind: 'una constante', what: 'cuánta gente puede entrar en una partida' },
  { key: 'version-guardado', kind: 'una constante', what: 'el número de versión del formato de guardado' },

  // ---- Funciones ----
  { key: 'aplicar-danio', kind: 'una función', what: 'quita vida a un enemigo y comprueba si muere', context: 'Recibe la cantidad de daño.' },
  { key: 'generar-nivel', kind: 'una función', what: 'crea un nivel aleatorio a partir de una semilla', context: 'Devuelve el nivel; no lo muestra.' },
  { key: 'cargar-partida', kind: 'una función', what: 'lee la partida guardada del disco y la aplica', context: 'Devuelve falso si no había partida.' },
  { key: 'guardar-partida', kind: 'una función', what: 'escribe el estado actual de la partida en disco' },
  { key: 'mover-hacia', kind: 'una función', what: 'acerca un enemigo a un punto a una velocidad dada, sin pasarse' },
  { key: 'distancia-jugador', kind: 'una función', what: 'devuelve a qué distancia está el jugador de un punto' },
  { key: 'reiniciar-nivel', kind: 'una función', what: 'vuelve a cargar el nivel actual desde el último punto de control' },
  { key: 'coste-mejora', kind: 'una función', what: 'calcula cuánto cuesta la siguiente mejora según el nivel actual' },
  { key: 'aparecer-enemigo', kind: 'una función', what: 'crea un enemigo en un punto de aparición libre' },
  { key: 'avanzar-dialogo', kind: 'una función', what: 'pasa a la siguiente línea de diálogo, o cierra la conversación si era la última' },
  { key: 'reproducir-sonido', kind: 'una función', what: 'reproduce un efecto de sonido con una pequeña variación de tono' },
  { key: 'esta-visible', kind: 'una función', what: 'dice si un punto está dentro de lo que ve la cámara' },
  { key: 'mezclar-lista', kind: 'una función', what: 'devuelve una copia desordenada de una lista' },
  { key: 'formatear-tiempo', kind: 'una función', what: 'convierte segundos en un texto como 01:45' },
  { key: 'enemigo-mas-cercano', kind: 'una función', what: 'devuelve el enemigo más cercano a un punto, o nada si no hay' },
  { key: 'aplicar-gravedad', kind: 'una función', what: 'añade la gravedad a la velocidad vertical en cada paso de física' },
  { key: 'cambiar-escena-fundido', kind: 'una función', what: 'cambia de escena con un fundido a negro' },
  { key: 'sacudir-camara', kind: 'una función', what: 'sacude la cámara durante un tiempo con una intensidad' },
  { key: 'soltar-botin', kind: 'una función', what: 'crea el botín de un enemigo al morir según su tabla' },
  { key: 'calcular-danio', kind: 'una función', what: 'calcula el daño final a partir del ataque, la defensa y el crítico' },
  { key: 'esta-en-rango', kind: 'una función', what: 'dice si un objetivo está a tiro' },
  { key: 'pausar-juego', kind: 'una función', what: 'pone el juego en pausa y muestra el menú' },
  { key: 'reanudar-juego', kind: 'una función', what: 'quita la pausa y oculta el menú' },
  { key: 'traducir', kind: 'una función', what: 'devuelve el texto en el idioma actual a partir de una clave' },
  { key: 'validar-nombre', kind: 'una función', what: 'comprueba que el nombre de jugador tiene entre 3 y 12 letras' },
  { key: 'ordenar-records', kind: 'una función', what: 'ordena la tabla de récords de mayor a menor' },
  { key: 'hacer-invulnerable', kind: 'una función', what: 'activa la invulnerabilidad durante unos segundos' },
  { key: 'cambiar-musica', kind: 'una función', what: 'cambia la música con un fundido cruzado' },
  { key: 'desbloquear-nivel', kind: 'una función', what: 'marca un nivel como desbloqueado y lo guarda' },
  { key: 'cargar-nivel', kind: 'una función', what: 'carga un nivel por su número' },
  { key: 'contar-enemigos-vivos', kind: 'una función', what: 'devuelve cuántos enemigos quedan vivos' },
  { key: 'generar-semilla', kind: 'una función', what: 'crea una semilla nueva a partir de la fecha' },
  { key: 'mundo-a-pantalla', kind: 'una función', what: 'convierte una posición del mundo a coordenadas de pantalla' },
  { key: 'interpolar-suave', kind: 'una función', what: 'acerca un valor a otro de forma suave según el tiempo' },

  // ---- Métodos ----
  { key: 'hay-espacio', kind: 'un método del inventario', what: 'dice si cabe un objeto más' },
  { key: 'anadir-objeto', kind: 'un método del inventario', what: 'mete un objeto y devuelve si ha cabido' },
  { key: 'recibir-golpe', kind: 'un método del enemigo', what: 'reacciona a un golpe: resta vida, reproduce el sonido y activa el parpadeo' },
  { key: 'entrar-estado', kind: 'un método de la máquina de estados', what: 'se ejecuta una vez al cambiar a un estado nuevo' },

  // ---- Clases y componentes ----
  { key: 'gestor-audio', kind: 'una clase', what: 'reproduce sonidos y música y controla el volumen', context: 'Solo hay una en todo el juego.' },
  { key: 'inventario', kind: 'una clase', what: 'guarda los objetos del jugador y cuántos tiene de cada uno' },
  { key: 'fabrica-niveles', kind: 'una clase', what: 'construye niveles a partir de una descripción' },
  { key: 'gestor-oleadas', kind: 'una clase', what: 'decide cuándo y cuántos enemigos aparecen' },
  { key: 'controlador-jugador', kind: 'un componente', what: 'lee la entrada y mueve al jugador' },
  { key: 'seguidor-camara', kind: 'un componente', what: 'hace que la cámara siga suavemente a un objetivo' },
  { key: 'daniable', kind: 'un componente', what: 'permite que cualquier objeto reciba daño y muera', context: 'Lo usan el jugador, los enemigos y las cajas.' },
  { key: 'gestor-guardado', kind: 'una clase', what: 'lee y escribe las partidas guardadas' },
  { key: 'gestor-escenas', kind: 'una clase', what: 'cambia de escena y controla los fundidos' },
  { key: 'gestor-dialogos', kind: 'una clase', what: 'muestra las conversaciones línea a línea' },
  { key: 'tabla-botin', kind: 'una clase', what: 'define qué objetos puede soltar un enemigo y con qué probabilidad' },
  { key: 'patrulla', kind: 'un componente', what: 'mueve a un enemigo entre varios puntos' },
  { key: 'recolectable', kind: 'un componente', what: 'hace que un objeto se recoja al tocarlo y dé algo' },
  { key: 'puerta', kind: 'un componente', what: 'abre y cierra una puerta con una llave o un interruptor' },
  { key: 'generador-enemigos', kind: 'un componente', what: 'crea enemigos cada cierto tiempo en un punto' },
  { key: 'mira-al-raton', kind: 'un componente', what: 'hace que un objeto mire hacia el ratón' },
  { key: 'temporizador-ronda', kind: 'una clase', what: 'cuenta el tiempo de la ronda y avisa cuando termina' },

  // ---- Enums ----
  { key: 'estado-enemigo', kind: 'un enum', what: 'los estados posibles de un enemigo: quieto, patrullando, persiguiendo, atacando' },
  { key: 'tipo-objeto', kind: 'un enum', what: 'los tipos de objeto del inventario: arma, consumible, llave, misión' },
  { key: 'dificultad', kind: 'un enum', what: 'los niveles de dificultad: fácil, normal, difícil' },
  { key: 'direccion', kind: 'un enum', what: 'las cuatro direcciones: arriba, abajo, izquierda, derecha' },
  { key: 'estado-partida', kind: 'un enum', what: 'los estados del juego: menú, jugando, pausa, fin' },
  { key: 'rareza', kind: 'un enum', what: 'la rareza de un objeto: común, rara, épica, legendaria' },
  { key: 'tipo-danio', kind: 'un enum', what: 'los tipos de daño: físico, fuego, hielo, veneno' },

  // ---- Eventos y señales ----
  { key: 'evento-muerte', kind: 'un evento', what: 'avisa a quien escuche de que el jugador ha muerto', context: 'Lo usan la interfaz, el audio y el sistema de reinicio.' },
  { key: 'evento-nivel-completado', kind: 'un evento', what: 'avisa de que se ha completado el nivel, con el tiempo empleado' },
  { key: 'senal-moneda', kind: 'una señal', what: 'se emite cuando el jugador recoge una moneda, con su valor' },
  { key: 'senal-vida-cambia', kind: 'una señal', what: 'se emite cada vez que cambia la vida, con el valor nuevo y el máximo' },
  { key: 'evento-pausa', kind: 'un evento', what: 'avisa de que el juego se ha pausado o reanudado' },
  { key: 'senal-puerta-abierta', kind: 'una señal', what: 'se emite cuando se abre una puerta, con su identificador' },
  { key: 'evento-oleada-terminada', kind: 'un evento', what: 'avisa de que ha terminado una oleada, con su número' },
  { key: 'senal-objeto-recogido', kind: 'una señal', what: 'se emite al recoger un objeto, con el objeto' },
  { key: 'evento-jefe-derrotado', kind: 'un evento', what: 'avisa de que el jefe ha caído' },

  // ---- Escenas, assets e interfaz ----
  { key: 'escena-menu', kind: 'una escena', what: 'el menú principal con jugar, opciones y salir', context: 'Es lo primero que se ve al abrir el juego.' },
  { key: 'escena-game-over', kind: 'una escena', what: 'la pantalla que aparece al perder, con reintentar y salir' },
  { key: 'escena-opciones', kind: 'una escena', what: 'el menú de opciones con volumen, idioma y controles' },
  { key: 'escena-creditos', kind: 'una escena', what: 'la pantalla de créditos' },
  { key: 'boton-pausa', kind: 'un asset', what: 'el sprite del botón de pausa en estado normal', context: 'Hay otro para cuando está pulsado.' },
  { key: 'fx-explosion', kind: 'un asset', what: 'el sistema de partículas de la explosión pequeña', context: 'Hay otra explosión grande para jefes.' },
  { key: 'musica-jefe', kind: 'un asset', what: 'la pista de música que suena en el combate contra el jefe' },
  { key: 'datos-arma', kind: 'un asset de datos', what: 'los datos de un arma: daño, cadencia y alcance' },
  { key: 'panel-victoria', kind: 'un prefab', what: 'el panel que aparece al ganar' },
  { key: 'texto-vidas', kind: 'un elemento de interfaz', what: 'el texto que muestra las vidas' },
  { key: 'mezclador', kind: 'un asset', what: 'el mezclador de audio con los canales de música, efectos y voces' },
  { key: 'animacion-caminar', kind: 'un asset', what: 'el clip de animación del personaje caminando' },
  { key: 'sonido-salto', kind: 'un asset', what: 'el efecto de sonido del salto' },
  { key: 'tileset-cueva', kind: 'un asset', what: 'el conjunto de tiles de los niveles de cueva' },
  { key: 'barra-vida', kind: 'un elemento de interfaz', what: 'la barra que muestra la vida del jugador' },
  { key: 'boton-reintentar', kind: 'un elemento de interfaz', what: 'el botón de volver a intentar el nivel' },
  { key: 'icono-llave', kind: 'un asset', what: 'el icono de la llave en el inventario' },
  { key: 'musica-menu', kind: 'un asset', what: 'la música del menú principal' },
  { key: 'sonido-golpe', kind: 'un asset', what: 'el efecto de sonido de recibir un golpe' },
  { key: 'material-agua', kind: 'un material', what: 'el material del agua con transparencia y ondas' },
  { key: 'shader-parpadeo', kind: 'un shader', what: 'pone el sprite en blanco un instante al recibir daño' },
  { key: 'animacion-morir', kind: 'un asset', what: 'el clip de animación de la muerte del personaje' },

  // ---- Capas y etiquetas ----
  { key: 'capa-plataformas', kind: 'una capa de física', what: 'las plataformas que se pueden atravesar desde abajo' },
  { key: 'capa-enemigos', kind: 'una capa de física', what: 'todo lo que puede hacer daño al jugador' },
  { key: 'tag-recogible', kind: 'una etiqueta', what: 'los objetos que el jugador puede recoger al tocarlos' },
  { key: 'tag-mortal', kind: 'una etiqueta', what: 'las zonas que matan al jugador al instante' },
];
